"""
Semantic cache implementation for Genie SQL queries using PostgreSQL pg_vector.

This module provides a semantic cache that uses embeddings and similarity search
to find cached queries that match the intent of new questions. Cache entries are
partitioned by genie_space_id to ensure proper isolation between Genie spaces.

The cache supports conversation-aware embedding using a rolling window approach
to capture context from recent conversation turns, improving accuracy for
multi-turn conversations with anaphoric references.
"""

from datetime import timedelta
from typing import Any

import mlflow
import pandas as pd
from databricks.sdk import WorkspaceClient
from databricks.sdk.service.dashboards import (
    GenieListConversationMessagesResponse,
    GenieMessage,
)
from databricks_ai_bridge.genie import GenieResponse
from loguru import logger

from dao_ai.config import (
    DatabaseModel,
    GenieSemanticCacheParametersModel,
    LLMModel,
    WarehouseModel,
)
from dao_ai.genie.cache.base import (
    CacheResult,
    GenieServiceBase,
    SQLCacheEntry,
)
from dao_ai.genie.cache.core import execute_sql_via_warehouse

# Type alias for database row (dict due to row_factory=dict_row)
DbRow = dict[str, Any]


def get_conversation_history(
    workspace_client: WorkspaceClient,
    space_id: str,
    conversation_id: str,
    max_messages: int = 10,
) -> list[GenieMessage]:
    """
    Retrieve conversation history from Genie.

    Args:
        workspace_client: The Databricks workspace client
        space_id: The Genie space ID
        conversation_id: The conversation ID to retrieve
        max_messages: Maximum number of messages to retrieve

    Returns:
        List of GenieMessage objects representing the conversation history
    """
    try:
        # Use the Genie API to retrieve conversation messages
        response: GenieListConversationMessagesResponse = (
            workspace_client.genie.list_conversation_messages(
                space_id=space_id,
                conversation_id=conversation_id,
            )
        )

        # Return the most recent messages up to max_messages
        if response.messages is not None:
            all_messages: list[GenieMessage] = list(response.messages)
            return (
                all_messages[-max_messages:]
                if len(all_messages) > max_messages
                else all_messages
            )
        return []
    except Exception as e:
        logger.warning(
            "Failed to retrieve conversation history",
            conversation_id=conversation_id,
            error=str(e),
        )
        return []


def build_context_string(
    question: str,
    conversation_messages: list[GenieMessage],
    window_size: int,
    max_tokens: int = 2000,
) -> str:
    """
    Build a context-aware question string using rolling window.

    This function creates a concatenated string that includes recent conversation
    turns to provide context for semantic similarity matching.

    Args:
        question: The current question
        conversation_messages: List of previous conversation messages
        window_size: Number of previous turns to include
        max_tokens: Maximum estimated tokens (rough approximation: 4 chars = 1 token)

    Returns:
        Context-aware question string formatted for embedding
    """
    if window_size <= 0 or not conversation_messages:
        return question

    # Take the last window_size messages (most recent)
    recent_messages = (
        conversation_messages[-window_size:]
        if len(conversation_messages) > window_size
        else conversation_messages
    )

    # Build context parts
    context_parts: list[str] = []

    for msg in recent_messages:
        # Only include messages with content from the history
        if msg.content:
            # Limit message length to prevent token overflow
            content: str = msg.content
            if len(content) > 500:  # Truncate very long messages
                content = content[:500] + "..."
            context_parts.append(f"Previous: {content}")

    # Add current question
    context_parts.append(f"Current: {question}")

    # Join with newlines
    context_string = "\n".join(context_parts)

    # Rough token limit check (4 chars ≈ 1 token)
    estimated_tokens = len(context_string) / 4
    if estimated_tokens > max_tokens:
        # Truncate to fit max_tokens
        target_chars = max_tokens * 4
        original_length = len(context_string)
        context_string = context_string[:target_chars] + "..."
        logger.trace(
            "Truncated context string",
            original_chars=original_length,
            target_chars=target_chars,
            max_tokens=max_tokens,
        )

    return context_string


class SemanticCacheService(GenieServiceBase):
    """
    Semantic caching decorator that uses PostgreSQL pg_vector for similarity lookup.

    This service caches the SQL query generated by Genie along with an embedding
    of the original question. On subsequent queries, it performs a semantic similarity
    search to find cached queries that match the intent of the new question.

    Cache entries are partitioned by genie_space_id to ensure queries from different
    Genie spaces don't return incorrect cache hits.

    On cache hit, it re-executes the cached SQL using the provided warehouse
    to return fresh data while avoiding the Genie NL-to-SQL translation cost.

    Example:
        from dao_ai.config import GenieSemanticCacheParametersModel, DatabaseModel
        from dao_ai.genie.cache import SemanticCacheService

        cache_params = GenieSemanticCacheParametersModel(
            database=database_model,
            warehouse=warehouse_model,
            embedding_model="databricks-gte-large-en",
            time_to_live_seconds=86400,  # 24 hours
            similarity_threshold=0.85
        )
        genie = SemanticCacheService(
            impl=GenieService(Genie(space_id="my-space")),
            parameters=cache_params
        )

    Thread-safe: Uses connection pooling from psycopg_pool.
    """

    impl: GenieServiceBase
    parameters: GenieSemanticCacheParametersModel
    workspace_client: WorkspaceClient | None
    name: str
    _embeddings: Any  # DatabricksEmbeddings
    _pool: Any  # ConnectionPool
    _embedding_dims: int | None
    _setup_complete: bool

    def __init__(
        self,
        impl: GenieServiceBase,
        parameters: GenieSemanticCacheParametersModel,
        workspace_client: WorkspaceClient | None = None,
        name: str | None = None,
    ) -> None:
        """
        Initialize the semantic cache service.

        Args:
            impl: The underlying GenieServiceBase to delegate to on cache miss.
                The space_id will be obtained from impl.space_id.
            parameters: Cache configuration including database, warehouse, embedding model
            workspace_client: Optional WorkspaceClient for retrieving conversation history.
                If None, conversation context will not be used.
            name: Name for this cache layer (for logging). Defaults to class name.
        """
        self.impl = impl
        self.parameters = parameters
        self.workspace_client = workspace_client
        self.name = name if name is not None else self.__class__.__name__
        self._embeddings = None
        self._pool = None
        self._embedding_dims = None
        self._setup_complete = False

    def initialize(self) -> "SemanticCacheService":
        """
        Eagerly initialize the cache service.

        Call this during tool creation to:
        - Validate configuration early (fail fast)
        - Create the database table before any requests
        - Avoid first-request latency from lazy initialization

        Returns:
            self for method chaining
        """
        self._setup()
        return self

    def _setup(self) -> None:
        """Initialize embeddings and database connection pool lazily."""
        if self._setup_complete:
            return

        from dao_ai.memory.postgres import PostgresPoolManager

        # Initialize embeddings
        # Convert embedding_model to LLMModel if it's a string
        embedding_model: LLMModel = (
            LLMModel(name=self.parameters.embedding_model)
            if isinstance(self.parameters.embedding_model, str)
            else self.parameters.embedding_model
        )
        self._embeddings = embedding_model.as_embeddings_model()

        # Auto-detect embedding dimensions if not provided
        if self.parameters.embedding_dims is None:
            sample_embedding: list[float] = self._embeddings.embed_query("test")
            self._embedding_dims = len(sample_embedding)
            logger.debug(
                "Auto-detected embedding dimensions",
                layer=self.name,
                dims=self._embedding_dims,
            )
        else:
            self._embedding_dims = self.parameters.embedding_dims

        # Get connection pool
        self._pool = PostgresPoolManager.get_pool(self.parameters.database)

        # Ensure table exists
        self._create_table_if_not_exists()

        self._setup_complete = True
        logger.debug(
            "Semantic cache initialized",
            layer=self.name,
            space_id=self.space_id,
            table_name=self.table_name,
            dims=self._embedding_dims,
        )

    @property
    def database(self) -> DatabaseModel:
        """The database used for storing cache entries."""
        return self.parameters.database

    @property
    def warehouse(self) -> WarehouseModel:
        """The warehouse used for executing cached SQL queries."""
        return self.parameters.warehouse

    @property
    def time_to_live(self) -> timedelta | None:
        """Time-to-live for cache entries. None means never expires."""
        ttl = self.parameters.time_to_live_seconds
        if ttl is None or ttl < 0:
            return None
        return timedelta(seconds=ttl)

    @property
    def similarity_threshold(self) -> float:
        """Minimum similarity for cache hit (using L2 distance converted to similarity)."""
        return self.parameters.similarity_threshold

    @property
    def embedding_dims(self) -> int:
        """Dimension size for embeddings (auto-detected if not configured)."""
        if self._embedding_dims is None:
            raise RuntimeError(
                "Embedding dimensions not yet initialized. Call _setup() first."
            )
        return self._embedding_dims

    @property
    def table_name(self) -> str:
        """Name of the cache table."""
        return self.parameters.table_name

    def _index_exists(self, cur: Any, index_name: str) -> bool:
        """Check if an index already exists in the database.

        Args:
            cur: Database cursor to execute SQL statements
            index_name: Name of the index to check

        Returns:
            True if the index exists, False otherwise
        """
        cur.execute(
            "SELECT 1 FROM pg_indexes WHERE indexname = %s",
            (index_name,),
        )
        return cur.fetchone() is not None

    def _create_table_if_not_exists(self) -> None:
        """Create the cache table and prompt history table with pg_vector extension if they don't exist.

        If the table exists but has a different embedding dimension, it will be
        dropped and recreated with the new dimension size.
        """
        create_extension_sql: str = "CREATE EXTENSION IF NOT EXISTS vector"

        # Check if table exists and get current embedding dimensions
        check_dims_sql: str = """
            SELECT atttypmod 
            FROM pg_attribute 
            WHERE attrelid = %s::regclass 
              AND attname = 'question_embedding'
        """

        create_table_sql: str = f"""
            CREATE TABLE IF NOT EXISTS {self.table_name} (
                id SERIAL PRIMARY KEY,
                genie_space_id TEXT NOT NULL,
                question TEXT NOT NULL,
                conversation_context TEXT,
                context_string TEXT,
                question_embedding vector({self.embedding_dims}),
                context_embedding vector({self.embedding_dims}),
                sql_query TEXT NOT NULL,
                description TEXT,
                conversation_id TEXT,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
            )
        """
        # Index for efficient similarity search partitioned by genie_space_id
        # Use L2 (Euclidean) distance - optimal for Databricks GTE embeddings
        create_question_embedding_index_sql: str = f"""
            CREATE INDEX IF NOT EXISTS {self.table_name}_question_embedding_idx 
            ON {self.table_name} 
            USING ivfflat (question_embedding vector_l2_ops)
            WITH (lists = 100)
        """
        create_context_embedding_index_sql: str = f"""
            CREATE INDEX IF NOT EXISTS {self.table_name}_context_embedding_idx 
            ON {self.table_name} 
            USING ivfflat (context_embedding vector_l2_ops)
            WITH (lists = 100)
        """
        # Index for filtering by genie_space_id
        create_space_index_sql: str = f"""
            CREATE INDEX IF NOT EXISTS {self.table_name}_space_idx 
            ON {self.table_name} (genie_space_id)
        """

        with self._pool.connection() as conn:
            with conn.cursor() as cur:
                cur.execute(create_extension_sql)

                # Check if table exists and verify embedding dimensions
                try:
                    cur.execute(check_dims_sql, (self.table_name,))
                    row: DbRow | None = cur.fetchone()
                    if row is not None:
                        # atttypmod for vector type contains the dimension
                        current_dims = row.get("atttypmod", 0)
                        if current_dims != self.embedding_dims:
                            logger.warning(
                                "Embedding dimension mismatch, dropping and recreating table",
                                layer=self.name,
                                table_dims=current_dims,
                                expected_dims=self.embedding_dims,
                                table_name=self.table_name,
                            )
                            cur.execute(f"DROP TABLE {self.table_name}")
                except Exception:
                    # Table doesn't exist, which is fine
                    pass

                try:
                    cur.execute(create_table_sql)
                except Exception as e:
                    # Table might already exist - that's ok
                    logger.debug(
                        f"Table creation skipped (may already exist): {e}",
                        layer=self.name,
                    )

                # Try to create indexes (skip if already exist to avoid permission errors
                # when table is owned by another user)
                for idx_name, idx_sql in [
                    (f"{self.table_name}_space_idx", create_space_index_sql),
                    (
                        f"{self.table_name}_question_embedding_idx",
                        create_question_embedding_index_sql,
                    ),
                    (
                        f"{self.table_name}_context_embedding_idx",
                        create_context_embedding_index_sql,
                    ),
                ]:
                    if self._index_exists(cur, idx_name):
                        logger.debug(
                            f"Index {idx_name} already exists, skipping creation",
                            layer=self.name,
                        )
                        continue
                    try:
                        cur.execute(idx_sql)
                    except Exception as e:
                        logger.warning(
                            f"Could not create {idx_name} (table may be owned by another user): {e}",
                            layer=self.name,
                        )

                # Create prompt history table (always enabled for conversation context)
                try:
                    self._create_prompt_history_table(cur)
                except Exception as e:
                    logger.error(
                        f"Failed to create prompt history table '{self.parameters.prompt_history_table}': {e}",
                        layer=self.name,
                        table_name=self.parameters.prompt_history_table,
                        exc_info=True,
                    )
                    # Don't raise - allow cache to work even if prompt history fails

    def _create_prompt_history_table(self, cur: Any) -> None:
        """Create the prompt history table for tracking user prompts.

        This table stores all user prompts (both cache hits and misses) to provide
        conversation context for semantic matching.

        Handles concurrent creation gracefully - if another process creates the
        table/index first, we treat that as success.

        Args:
            cur: Database cursor to execute SQL statements
        """
        prompt_table_name = self.parameters.prompt_history_table

        create_prompt_table_sql: str = f"""
            CREATE TABLE IF NOT EXISTS {prompt_table_name} (
                id SERIAL PRIMARY KEY,
                genie_space_id TEXT NOT NULL,
                conversation_id TEXT NOT NULL,
                prompt TEXT NOT NULL,
                cache_hit BOOLEAN DEFAULT FALSE,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
            )
        """

        # Index for efficient conversation history retrieval
        create_conversation_index_sql: str = f"""
            CREATE INDEX IF NOT EXISTS {prompt_table_name}_conversation_idx 
            ON {prompt_table_name} (genie_space_id, conversation_id, created_at DESC)
        """

        # Index for efficient space-wide queries
        create_space_index_sql: str = f"""
            CREATE INDEX IF NOT EXISTS {prompt_table_name}_space_idx 
            ON {prompt_table_name} (genie_space_id, created_at DESC)
        """

        logger.debug(
            "Creating prompt history table and indexes",
            layer=self.name,
            table=prompt_table_name,
            space_id=self.space_id,
        )

        # Handle concurrent creation - another process may create these first
        # PostgreSQL can throw "duplicate key" errors on concurrent IF NOT EXISTS
        try:
            cur.execute(create_prompt_table_sql)
        except Exception as e:
            if "duplicate key" in str(e) or "already exists" in str(e):
                logger.debug(
                    "Prompt history table already exists (concurrent creation)",
                    layer=self.name,
                    table=prompt_table_name,
                )
            else:
                raise

        # Create indexes (skip if already exist to avoid permission errors
        # when table is owned by another user)
        for idx_name, idx_sql in [
            (f"{prompt_table_name}_conversation_idx", create_conversation_index_sql),
            (f"{prompt_table_name}_space_idx", create_space_index_sql),
        ]:
            if self._index_exists(cur, idx_name):
                logger.debug(
                    f"Index {idx_name} already exists, skipping creation",
                    layer=self.name,
                )
                continue
            try:
                cur.execute(idx_sql)
            except Exception as e:
                if "duplicate key" in str(e) or "already exists" in str(e):
                    logger.debug(
                        f"Index {idx_name} already exists (concurrent creation)",
                        layer=self.name,
                    )
                else:
                    # Log warning but don't fail - indexes are optimization, not required
                    logger.warning(
                        f"Could not create index {idx_name}: {e}",
                        layer=self.name,
                    )

        logger.info(
            "Prompt history table ready",
            layer=self.name,
            table=prompt_table_name,
            indexes=[
                f"{prompt_table_name}_conversation_idx",
                f"{prompt_table_name}_space_idx",
            ],
        )

    def _store_user_prompt(
        self,
        prompt: str,
        conversation_id: str,
        cache_hit: bool = False,
    ) -> bool:
        """Store user prompt in local conversation history.

        This is called after embeddings are generated to ensure the current prompt
        is not included in its own context.

        Prompt history is non-critical; failures are logged but don't crash the request.

        Args:
            prompt: The user's question/prompt
            conversation_id: The conversation ID
            cache_hit: Whether this prompt resulted in a cache hit

        Returns:
            True if prompt was stored successfully, False otherwise
        """
        prompt_table_name = self.parameters.prompt_history_table
        insert_sql: str = f"""
            INSERT INTO {prompt_table_name} 
            (genie_space_id, conversation_id, prompt, cache_hit)
            VALUES (%s, %s, %s, %s)
        """

        logger.debug(
            "Inserting prompt into history",
            layer=self.name,
            table=prompt_table_name,
            space_id=self.space_id,
            conversation_id=conversation_id,
            prompt_preview=prompt[:80] if len(prompt) > 80 else prompt,
            prompt_length=len(prompt),
            cache_hit=cache_hit,
        )

        try:
            with self._pool.connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(
                        insert_sql, (self.space_id, conversation_id, prompt, cache_hit)
                    )

            logger.info(
                "Stored user prompt in history",
                layer=self.name,
                table=prompt_table_name,
                conversation_id=conversation_id,
                prompt_preview=prompt[:50],
                cache_hit=cache_hit,
            )

            # Enforce max_prompt_history_length per conversation
            self._enforce_prompt_history_limit(conversation_id)

            return True
        except Exception as e:
            logger.warning(
                f"Failed to store prompt in history (non-critical): {e}",
                layer=self.name,
                table=prompt_table_name,
                conversation_id=conversation_id,
            )
            return False

    def _enforce_prompt_history_limit(self, conversation_id: str) -> int:
        """Delete oldest prompts if conversation exceeds max_prompt_history_length.

        This is called after inserting a new prompt to keep history bounded.
        Uses a single DELETE with subquery for efficiency.

        Args:
            conversation_id: The conversation ID to enforce limit for

        Returns:
            Number of prompts deleted (0 if within limit)
        """
        max_length = self.parameters.max_prompt_history_length
        prompt_table_name = self.parameters.prompt_history_table

        # Delete prompts beyond the limit, keeping the most recent ones
        # Uses subquery to find prompts older than the Nth most recent
        delete_sql: str = f"""
            DELETE FROM {prompt_table_name}
            WHERE genie_space_id = %s 
              AND conversation_id = %s
              AND created_at < (
                  SELECT created_at FROM {prompt_table_name}
                  WHERE genie_space_id = %s 
                    AND conversation_id = %s
                  ORDER BY created_at DESC
                  LIMIT 1 OFFSET %s
              )
        """

        try:
            with self._pool.connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(
                        delete_sql,
                        (
                            self.space_id,
                            conversation_id,
                            self.space_id,
                            conversation_id,
                            max_length - 1,
                        ),
                    )
                    deleted = cur.rowcount if isinstance(cur.rowcount, int) else 0

                    if deleted > 0:
                        logger.debug(
                            "Enforced prompt history limit",
                            layer=self.name,
                            table=prompt_table_name,
                            conversation_id=conversation_id,
                            max_length=max_length,
                            deleted=deleted,
                        )
                    return deleted
        except Exception as e:
            logger.debug(
                f"Failed to enforce prompt history limit (non-critical): {e}",
                layer=self.name,
                conversation_id=conversation_id,
            )
            return 0

    def _get_local_prompt_history(
        self,
        conversation_id: str,
        max_prompts: int | None = None,
    ) -> list[str]:
        """
        Retrieve recent user prompts from local storage.

        Uses SQL LIMIT for efficiency - only retrieves exactly the number
        of prompts needed for the context window, not all prompts.

        Args:
            conversation_id: The conversation ID to retrieve prompts for
            max_prompts: Maximum number of prompts (matches context_window_size).
                        If None, uses self.parameters.context_window_size

        Returns:
            List of prompt strings in chronological order (oldest to newest)
        """
        if max_prompts is None:
            max_prompts = self.parameters.context_window_size

        prompt_table_name = self.parameters.prompt_history_table
        query_sql: str = f"""
            SELECT prompt 
            FROM {prompt_table_name}
            WHERE genie_space_id = %s 
              AND conversation_id = %s
            ORDER BY created_at DESC
            LIMIT %s
        """

        logger.debug(
            "Querying prompt history",
            layer=self.name,
            table=prompt_table_name,
            space_id=self.space_id,
            conversation_id=conversation_id,
            max_prompts=max_prompts,
        )

        with self._pool.connection() as conn:
            with conn.cursor() as cur:
                # LIMIT ensures we only fetch exactly what's needed
                cur.execute(query_sql, (self.space_id, conversation_id, max_prompts))
                rows: list[DbRow] = cur.fetchall()
                # Reverse to get chronological order (oldest to newest)
                prompts = [row["prompt"] for row in reversed(rows)]

                logger.info(
                    "Retrieved prompt history from database",
                    layer=self.name,
                    table=prompt_table_name,
                    conversation_id=conversation_id,
                    requested=max_prompts,
                    returned=len(prompts),
                    prompts_preview=[
                        p[:40] + "..." if len(p) > 40 else p for p in prompts
                    ],
                )

                return prompts

    def _update_prompt_cache_hit(
        self,
        conversation_id: str,
        prompt: str,
        cache_hit: bool,
    ) -> bool:
        """Update the cache_hit flag for a previously stored prompt.

        This is called after determining whether the prompt resulted in a cache hit.
        Updates the most recent prompt matching the given text.

        Prompt history updates are non-critical; failures are logged but don't crash.

        Args:
            conversation_id: The conversation ID
            prompt: The prompt text to update
            cache_hit: The cache hit status to set

        Returns:
            True if update was successful, False otherwise
        """
        prompt_table_name = self.parameters.prompt_history_table
        update_sql: str = f"""
            UPDATE {prompt_table_name}
            SET cache_hit = %s
            WHERE genie_space_id = %s 
              AND conversation_id = %s 
              AND prompt = %s 
              AND created_at = (
                  SELECT MAX(created_at) 
                  FROM {prompt_table_name}
                  WHERE genie_space_id = %s 
                    AND conversation_id = %s 
                    AND prompt = %s
              )
        """

        logger.debug(
            "Updating prompt cache_hit flag",
            layer=self.name,
            table=prompt_table_name,
            space_id=self.space_id,
            conversation_id=conversation_id,
            prompt_preview=prompt[:50],
            new_cache_hit=cache_hit,
        )

        try:
            with self._pool.connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(
                        update_sql,
                        (
                            cache_hit,
                            self.space_id,
                            conversation_id,
                            prompt,
                            self.space_id,
                            conversation_id,
                            prompt,
                        ),
                    )
                    # Handle rowcount safely (may be Mock in tests or None)
                    updated_rows = getattr(cur, "rowcount", 0)
                    if not isinstance(updated_rows, int):
                        updated_rows = 0

                    if updated_rows > 0:
                        logger.info(
                            "Updated prompt cache_hit flag in history",
                            layer=self.name,
                            table=prompt_table_name,
                            conversation_id=conversation_id,
                            prompt_preview=prompt[:50],
                            cache_hit=cache_hit,
                            rows_updated=updated_rows,
                        )
                        return True
                    else:
                        logger.debug(
                            "No prompt found to update cache_hit flag (may be expected)",
                            layer=self.name,
                            table=prompt_table_name,
                            conversation_id=conversation_id,
                            prompt_preview=prompt[:50],
                        )
                        return False
        except Exception as e:
            logger.warning(
                f"Failed to update prompt cache_hit flag (non-critical): {e}",
                layer=self.name,
                table=prompt_table_name,
                conversation_id=conversation_id,
            )
            return False

    def _embed_question(
        self, question: str, conversation_id: str | None = None
    ) -> tuple[list[float], list[float], str]:
        """
        Generate dual embeddings: one for the question, one for the conversation context.

        This enables separate matching of question similarity vs context similarity,
        improving precision by ensuring both the question AND the conversation context
        are semantically similar before returning a cached result.

        Args:
            question: The question to embed
            conversation_id: Optional conversation ID for retrieving context

        Returns:
            Tuple of (question_embedding, context_embedding, conversation_context_string)
            - question_embedding: Vector embedding of just the question
            - context_embedding: Vector embedding of the conversation context (or zero vector if no context)
            - conversation_context_string: The conversation context string (empty if no context)
        """
        conversation_context = ""

        # If conversation context is enabled and available
        if conversation_id is not None and self.parameters.context_window_size > 0:
            try:
                # Try local prompt history first (FASTER, includes cache hits)
                recent_prompts = self._get_local_prompt_history(
                    conversation_id=conversation_id,
                    max_prompts=self.parameters.context_window_size,
                )

                logger.trace(
                    "Retrieved local prompt history",
                    layer=self.name,
                    prompts_count=len(recent_prompts),
                    conversation_id=conversation_id,
                )

                # Fallback to Genie API if local history empty and API available
                if (
                    not recent_prompts
                    and self.workspace_client is not None
                    and self.parameters.use_genie_api_for_history
                ):
                    logger.debug(
                        "Local prompt history empty, falling back to Genie API",
                        layer=self.name,
                        conversation_id=conversation_id,
                    )

                    conversation_messages = get_conversation_history(
                        workspace_client=self.workspace_client,
                        space_id=self.space_id,
                        conversation_id=conversation_id,
                        max_messages=self.parameters.context_window_size
                        * 2,  # Get extra for safety
                    )

                    # Extract user messages only (filter out assistant responses)
                    if conversation_messages:
                        recent_messages = (
                            conversation_messages[
                                -self.parameters.context_window_size :
                            ]
                            if len(conversation_messages)
                            > self.parameters.context_window_size
                            else conversation_messages
                        )
                        # TODO: Filter by role if GenieMessage has role field
                        # For now, use all messages as before
                        recent_prompts = [
                            msg.content for msg in recent_messages if msg.content
                        ]

                # Build context string from prompts
                if recent_prompts:
                    context_parts: list[str] = []
                    for prompt in recent_prompts:
                        content: str = prompt
                        if len(content) > 500:
                            content = content[:500] + "..."
                        context_parts.append(f"Previous: {content}")

                    conversation_context = "\n".join(context_parts)

                    # Truncate if too long
                    estimated_tokens = len(conversation_context) / 4
                    if estimated_tokens > self.parameters.max_context_tokens:
                        target_chars = self.parameters.max_context_tokens * 4
                        conversation_context = (
                            conversation_context[:target_chars] + "..."
                        )

                    logger.trace(
                        "Using conversation context",
                        layer=self.name,
                        prompts_count=len(recent_prompts),
                        window_size=self.parameters.context_window_size,
                        source="local_db",
                    )
            except Exception as e:
                logger.warning(
                    "Failed to build conversation context, using question only",
                    layer=self.name,
                    error=str(e),
                )
                conversation_context = ""

        # Generate dual embeddings
        if conversation_context:
            # Embed both question and context
            embeddings: list[list[float]] = self._embeddings.embed_documents(
                [question, conversation_context]
            )
            question_embedding = embeddings[0]
            context_embedding = embeddings[1]
        else:
            # Only embed question, use zero vector for context
            embeddings = self._embeddings.embed_documents([question])
            question_embedding = embeddings[0]
            context_embedding = [0.0] * len(question_embedding)  # Zero vector

        return question_embedding, context_embedding, conversation_context

    @mlflow.trace(name="semantic_search")
    def _find_similar(
        self,
        question: str,
        conversation_context: str,
        question_embedding: list[float],
        context_embedding: list[float],
        conversation_id: str | None = None,
    ) -> tuple[SQLCacheEntry, float] | None:
        """
        Find a semantically similar cached entry using dual embedding matching.

        This method matches BOTH the question AND the conversation context separately,
        ensuring high precision by requiring both to be semantically similar.

        Args:
            question: The original question (for logging)
            conversation_context: The conversation context string
            question_embedding: The embedding vector of just the question
            context_embedding: The embedding vector of the conversation context
            conversation_id: Optional conversation ID (for logging)

        Returns:
            Tuple of (SQLCacheEntry, combined_similarity_score) if found, None otherwise
        """
        # Use L2 (Euclidean) distance - optimal for Databricks GTE embeddings
        # pg_vector's <-> operator returns L2 distance (0 = identical)
        # Convert to similarity: 1 / (1 + distance) gives range [0, 1]
        #
        # Dual embedding strategy:
        # 1. Calculate separate similarities for question and context
        # 2. BOTH must exceed their respective thresholds
        # 3. Combined score is weighted average
        # 4. Refresh-on-hit: check TTL after similarity check
        ttl_seconds = self.parameters.time_to_live_seconds
        ttl_disabled = ttl_seconds is None or ttl_seconds < 0

        # When TTL is disabled, all entries are always valid
        if ttl_disabled:
            is_valid_expr = "TRUE"
        else:
            is_valid_expr = f"created_at > NOW() - INTERVAL '{ttl_seconds} seconds'"

        # Weighted combined similarity for ordering
        question_weight: float = self.parameters.question_weight
        context_weight: float = self.parameters.context_weight

        search_sql: str = f"""
            SELECT 
                id,
                question,
                conversation_context,
                sql_query,
                description,
                conversation_id,
                created_at,
                1.0 / (1.0 + (question_embedding <-> %s::vector)) as question_similarity,
                1.0 / (1.0 + (context_embedding <-> %s::vector)) as context_similarity,
                ({question_weight} * (1.0 / (1.0 + (question_embedding <-> %s::vector)))) +
                ({context_weight} * (1.0 / (1.0 + (context_embedding <-> %s::vector)))) as combined_similarity,
                {is_valid_expr} as is_valid
            FROM {self.table_name}
            WHERE genie_space_id = %s
            ORDER BY combined_similarity DESC
            LIMIT 1
        """

        question_emb_str: str = f"[{','.join(str(x) for x in question_embedding)}]"
        context_emb_str: str = f"[{','.join(str(x) for x in context_embedding)}]"

        with self._pool.connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    search_sql,
                    (
                        question_emb_str,
                        context_emb_str,
                        question_emb_str,
                        context_emb_str,
                        self.space_id,
                    ),
                )
                row: DbRow | None = cur.fetchone()

                if row is None:
                    logger.info(
                        "Cache MISS (no entries)",
                        layer=self.name,
                        question=question[:50],
                        space=self.space_id,
                        delegating_to=type(self.impl).__name__,
                    )
                    return None

                # Extract values from dict row
                entry_id: Any = row.get("id")
                cached_question: str = row.get("question", "")
                cached_context: str = row.get("conversation_context", "")
                sql_query: str = row["sql_query"]
                description: str = row.get("description", "")
                conversation_id_cached: str = row.get("conversation_id", "")
                created_at: Any = row["created_at"]
                question_similarity: float = row["question_similarity"]
                context_similarity: float = row["context_similarity"]
                combined_similarity: float = row["combined_similarity"]
                is_valid: bool = row.get("is_valid", False)

                # Log best match info
                logger.debug(
                    "Best match found",
                    layer=self.name,
                    question_sim=f"{question_similarity:.4f}",
                    context_sim=f"{context_similarity:.4f}",
                    combined_sim=f"{combined_similarity:.4f}",
                    is_valid=is_valid,
                    cached_question=cached_question[:50],
                    cached_context=cached_context[:80],
                )

                # Check BOTH similarity thresholds (dual embedding precision check)
                if question_similarity < self.parameters.similarity_threshold:
                    logger.info(
                        "Cache MISS (question similarity too low)",
                        layer=self.name,
                        question_sim=f"{question_similarity:.4f}",
                        threshold=self.parameters.similarity_threshold,
                        delegating_to=type(self.impl).__name__,
                    )
                    return None

                if context_similarity < self.parameters.context_similarity_threshold:
                    logger.info(
                        "Cache MISS (context similarity too low)",
                        layer=self.name,
                        context_sim=f"{context_similarity:.4f}",
                        threshold=self.parameters.context_similarity_threshold,
                        delegating_to=type(self.impl).__name__,
                    )
                    return None

                # Check TTL - refresh on hit strategy
                if not is_valid:
                    # Entry is expired - delete it and return miss to trigger refresh
                    delete_sql = f"DELETE FROM {self.table_name} WHERE id = %s"
                    cur.execute(delete_sql, (entry_id,))
                    logger.info(
                        "Cache MISS (expired, deleted for refresh)",
                        layer=self.name,
                        combined_sim=f"{combined_similarity:.4f}",
                        ttl_seconds=ttl_seconds,
                        cached_question=cached_question[:50],
                        delegating_to=type(self.impl).__name__,
                    )
                    return None

                from datetime import datetime as dt

                cache_age_seconds = (
                    (dt.now(created_at.tzinfo) - created_at).total_seconds()
                    if created_at
                    else None
                )
                logger.info(
                    "Cache HIT",
                    layer=self.name,
                    question=question[:80],
                    conversation_id=conversation_id,
                    matched_question=cached_question[:80],
                    cache_age_seconds=round(cache_age_seconds, 1)
                    if cache_age_seconds
                    else None,
                    question_similarity=f"{question_similarity:.4f}",
                    context_similarity=f"{context_similarity:.4f}",
                    combined_similarity=f"{combined_similarity:.4f}",
                    cached_sql=sql_query[:80] if sql_query else None,
                    ttl_seconds=self.parameters.time_to_live_seconds,
                )

                entry = SQLCacheEntry(
                    query=sql_query,
                    description=description,
                    conversation_id=conversation_id_cached,
                    created_at=created_at,
                )
                return entry, combined_similarity

    def _store_entry(
        self,
        question: str,
        conversation_context: str,
        question_embedding: list[float],
        context_embedding: list[float],
        response: GenieResponse,
    ) -> None:
        """Store a new cache entry with dual embeddings for this Genie space."""
        insert_sql: str = f"""
            INSERT INTO {self.table_name} 
            (genie_space_id, question, conversation_context, context_string, 
             question_embedding, context_embedding, sql_query, description, conversation_id)
            VALUES (%s, %s, %s, %s, %s::vector, %s::vector, %s, %s, %s)
        """
        question_emb_str: str = f"[{','.join(str(x) for x in question_embedding)}]"
        context_emb_str: str = f"[{','.join(str(x) for x in context_embedding)}]"

        # Build full context string for backward compatibility (used in logging)
        if conversation_context:
            full_context_string = f"{conversation_context}\nCurrent: {question}"
        else:
            full_context_string = question

        with self._pool.connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    insert_sql,
                    (
                        self.space_id,
                        question,
                        conversation_context,
                        full_context_string,
                        question_emb_str,
                        context_emb_str,
                        response.query,
                        response.description,
                        response.conversation_id,
                    ),
                )
                logger.debug(
                    "Stored cache entry",
                    layer=self.name,
                    question=question[:50],
                    context=conversation_context[:80],
                    sql=response.query[:50] if response.query else None,
                    space=self.space_id,
                    table=self.table_name,
                )

    @mlflow.trace(name="execute_cached_sql_semantic")
    def _execute_sql(self, sql: str) -> pd.DataFrame | str:
        """Execute SQL using the warehouse and return results."""
        # Use shared utility function for SQL execution
        return execute_sql_via_warehouse(
            warehouse=self.warehouse,
            sql=sql,
            layer_name=self.name,
        )

    def ask_question(
        self, question: str, conversation_id: str | None = None
    ) -> CacheResult:
        """
        Ask a question, using semantic cache if a similar query exists.

        On cache hit, re-executes the cached SQL to get fresh data.
        Returns CacheResult with cache metadata.
        """
        return self.ask_question_with_cache_info(question, conversation_id)

    @mlflow.trace(name="genie_semantic_cache_lookup")
    def ask_question_with_cache_info(
        self,
        question: str,
        conversation_id: str | None = None,
    ) -> CacheResult:
        """
        Ask a question with detailed cache hit information.

        On cache hit, the cached SQL is re-executed to return fresh data, but the
        conversation_id returned is the current conversation_id (not the cached one).

        CRITICAL ORDER:
        1. Retrieve PREVIOUS prompts from history (before storing current)
        2. Build embeddings using previous prompts as context
        3. Store current prompt in history (after context built)
        4. Search cache
        5. Update cache_hit flag if hit

        Args:
            question: The question to ask
            conversation_id: Optional conversation ID for context and continuation

        Returns:
            CacheResult with fresh response and cache metadata
        """
        # Ensure initialization (lazy init if initialize() wasn't called)
        self._setup()

        # Step 1 & 2: Generate dual embeddings BEFORE storing current prompt
        # This ensures context contains PREVIOUS prompts only, not the current one
        # _embed_question() will retrieve previous prompts from local storage
        question_embedding: list[float]
        context_embedding: list[float]
        conversation_context: str
        question_embedding, context_embedding, conversation_context = (
            self._embed_question(question, conversation_id)
        )

        # Step 3: Store prompt with current conversation_id (if available)
        # If conversation_id is None, we'll store it after getting response from Genie
        # This way the current prompt won't be included in its own context
        prompt_stored = False
        if conversation_id:
            self._store_user_prompt(
                prompt=question,
                conversation_id=conversation_id,
                cache_hit=False,  # Initially assume miss, update later if hit
            )
            prompt_stored = True

        # Check cache using dual embedding similarity
        cache_result: tuple[SQLCacheEntry, float] | None = self._find_similar(
            question,
            conversation_context,
            question_embedding,
            context_embedding,
            conversation_id,
        )

        if cache_result is not None:
            cached, combined_similarity = cache_result
            logger.debug(
                "Semantic cache hit",
                layer=self.name,
                combined_similarity=f"{combined_similarity:.3f}",
                question=question[:50],
                conversation_id=conversation_id,
            )

            # Re-execute the cached SQL to get fresh data
            result: pd.DataFrame | str = self._execute_sql(cached.query)

            # Check if SQL execution failed (returns error string instead of DataFrame)
            if isinstance(result, str):
                logger.warning(
                    "Cached SQL execution failed, falling back to Genie",
                    layer=self.name,
                    question=question[:80],
                    conversation_id=conversation_id,
                    cached_sql=cached.query[:80],
                    error=result[:200],
                    space_id=self.space_id,
                    table=self.table_name,
                )

                # Delete the stale cache entry from database
                delete_sql = f"DELETE FROM {self.table_name} WHERE genie_space_id = %s AND question = %s"
                with self._pool.connection() as conn:
                    with conn.cursor() as cur:
                        cur.execute(delete_sql, (self.space_id, question))
                        deleted_rows = cur.rowcount
                        logger.info(
                            "Deleted stale cache entry from database",
                            layer=self.name,
                            deleted_rows=deleted_rows,
                            space_id=self.space_id,
                            table=self.table_name,
                        )

                # Fall back to Genie to get fresh SQL
                logger.info(
                    "Delegating to Genie for fresh SQL",
                    layer=self.name,
                    question=question[:80],
                    conversation_id=conversation_id,
                    space_id=self.space_id,
                    delegating_to=type(self.impl).__name__,
                )
                fallback_result: CacheResult = self.impl.ask_question(
                    question, conversation_id
                )

                # Store the fresh SQL in cache
                if fallback_result.response.query:
                    self._store_entry(
                        question,
                        conversation_context,
                        question_embedding,
                        context_embedding,
                        fallback_result.response,
                    )
                    logger.info(
                        "Stored fresh SQL from fallback in database",
                        layer=self.name,
                        fresh_sql=fallback_result.response.query[:80],
                        space_id=self.space_id,
                        table=self.table_name,
                    )
                else:
                    logger.warning(
                        "Fallback response has no SQL query to cache",
                        layer=self.name,
                        question=question[:80],
                        space_id=self.space_id,
                    )

                logger.info(
                    "Fallback completed successfully",
                    layer=self.name,
                    question=question[:80],
                    conversation_id=conversation_id,
                    space_id=self.space_id,
                    fallback_from="stale_cache",
                    has_result=fallback_result.response.result is not None,
                )

                # Return as cache miss (fallback scenario)
                return CacheResult(
                    response=fallback_result.response,
                    cache_hit=False,
                    served_by=None,
                )

            # IMPORTANT: Use the current conversation_id (from the request), not the cached one
            # This ensures the conversation continues properly
            response: GenieResponse = GenieResponse(
                result=result,
                query=cached.query,
                description=cached.description,
                conversation_id=conversation_id
                if conversation_id
                else cached.conversation_id,
            )

            # Step 5: Update cache_hit flag for the stored prompt
            # Use the conversation_id from response (handles case where input was None)
            actual_conv_id = response.conversation_id or conversation_id
            if actual_conv_id and prompt_stored:
                self._update_prompt_cache_hit(
                    conversation_id=actual_conv_id,
                    prompt=question,
                    cache_hit=True,
                )

            return CacheResult(response=response, cache_hit=True, served_by=self.name)

        # Cache miss - delegate to wrapped service
        logger.info(
            "Cache MISS",
            layer=self.name,
            question=question[:80],
            conversation_id=conversation_id,
            space_id=self.space_id,
            similarity_threshold=self.similarity_threshold,
            delegating_to=type(self.impl).__name__,
        )

        result: CacheResult = self.impl.ask_question(question, conversation_id)

        # If conversation_id was None initially, store the prompt now with the actual conversation_id
        if not prompt_stored and result.response.conversation_id:
            self._store_user_prompt(
                prompt=question,
                conversation_id=result.response.conversation_id,
                cache_hit=False,
            )

        # Store in cache if we got a SQL query
        if result.response.query:
            logger.debug(
                "Storing new cache entry",
                layer=self.name,
                question=question[:50],
                conversation_id=conversation_id,
                space=self.space_id,
            )
            self._store_entry(
                question,
                conversation_context,
                question_embedding,
                context_embedding,
                result.response,
            )
        elif not result.response.query:
            logger.warning(
                "Not caching: response has no SQL query",
                layer=self.name,
                question=question[:50],
            )

        return CacheResult(response=result.response, cache_hit=False, served_by=None)

    @property
    def space_id(self) -> str:
        return self.impl.space_id

    def invalidate_expired(self) -> dict[str, int]:
        """Remove expired entries from the cache and prompt history for this Genie space.

        Returns dict with 'cache' and 'prompt_history' counts.
        Returns {'cache': 0, 'prompt_history': 0} if TTL is disabled.
        """
        self._setup()
        ttl_seconds = self.parameters.time_to_live_seconds
        prompt_ttl_seconds = self.parameters.prompt_history_ttl_seconds

        # Use cache TTL for prompt history if not explicitly set
        if prompt_ttl_seconds is None:
            prompt_ttl_seconds = ttl_seconds

        result = {"cache": 0, "prompt_history": 0}

        # Clean up cache entries
        if ttl_seconds is not None and ttl_seconds >= 0:
            delete_cache_sql: str = f"""
                DELETE FROM {self.table_name}
                WHERE genie_space_id = %s
                  AND created_at < NOW() - INTERVAL '%s seconds'
            """

            with self._pool.connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(delete_cache_sql, (self.space_id, ttl_seconds))
                    deleted: int = cur.rowcount if isinstance(cur.rowcount, int) else 0
                    result["cache"] = deleted
                    logger.debug(
                        "Deleted expired cache entries",
                        layer=self.name,
                        deleted_count=deleted,
                        space=self.space_id,
                        ttl_seconds=ttl_seconds,
                    )
        else:
            logger.trace(
                "Cache TTL disabled, no cache entries to expire",
                layer=self.name,
                space=self.space_id,
            )

        # Clean up prompt history entries
        if prompt_ttl_seconds is not None and prompt_ttl_seconds >= 0:
            prompt_table = self.parameters.prompt_history_table
            delete_prompt_sql: str = f"""
                DELETE FROM {prompt_table}
                WHERE genie_space_id = %s
                  AND created_at < NOW() - INTERVAL '%s seconds'
            """

            try:
                with self._pool.connection() as conn:
                    with conn.cursor() as cur:
                        cur.execute(
                            delete_prompt_sql, (self.space_id, prompt_ttl_seconds)
                        )
                        deleted = cur.rowcount if isinstance(cur.rowcount, int) else 0
                        result["prompt_history"] = deleted
                        logger.debug(
                            "Deleted expired prompt history entries",
                            layer=self.name,
                            deleted_count=deleted,
                            space=self.space_id,
                            ttl_seconds=prompt_ttl_seconds,
                        )
            except Exception as e:
                logger.warning(
                    f"Failed to clean up prompt history (non-critical): {e}",
                    layer=self.name,
                    space=self.space_id,
                )
        else:
            logger.trace(
                "Prompt history TTL disabled, no prompt history to expire",
                layer=self.name,
                space=self.space_id,
            )

        return result

    def clear(self) -> int:
        """Clear all entries from the cache for this Genie space."""
        self._setup()
        delete_sql: str = f"DELETE FROM {self.table_name} WHERE genie_space_id = %s"

        with self._pool.connection() as conn:
            with conn.cursor() as cur:
                cur.execute(delete_sql, (self.space_id,))
                deleted: int = cur.rowcount
                logger.debug(
                    "Cleared cache entries",
                    layer=self.name,
                    deleted_count=deleted,
                    space=self.space_id,
                )
                return deleted

    def get_prompt_history(
        self,
        conversation_id: str,
        max_prompts: int | None = None,
        include_cache_hits: bool = True,
    ) -> list[dict[str, any]]:
        """
        Retrieve prompt history for a conversation with metadata.

        Public utility method for inspecting conversation history.

        Args:
            conversation_id: The conversation ID to retrieve
            max_prompts: Maximum number of prompts (None = all prompts)
            include_cache_hits: Whether to include prompts that hit cache

        Returns:
            List of prompt records with metadata (prompt, cache_hit, created_at)
        """
        self._setup()

        prompt_table_name = self.parameters.prompt_history_table

        cache_filter = "" if include_cache_hits else "AND cache_hit = false"
        limit_clause = f"LIMIT {max_prompts}" if max_prompts else ""

        query_sql: str = f"""
            SELECT prompt, cache_hit, created_at
            FROM {prompt_table_name}
            WHERE genie_space_id = %s 
              AND conversation_id = %s
              {cache_filter}
            ORDER BY created_at ASC
            {limit_clause}
        """

        with self._pool.connection() as conn:
            with conn.cursor() as cur:
                cur.execute(query_sql, (self.space_id, conversation_id))
                rows: list[DbRow] = cur.fetchall()

                return [
                    {
                        "prompt": row["prompt"],
                        "cache_hit": row["cache_hit"],
                        "created_at": row["created_at"],
                    }
                    for row in rows
                ]

    def export_prompt_history(
        self,
        conversation_id: str,
        output_format: str = "text",
    ) -> str:
        """
        Export prompt history for a conversation in various formats.

        Args:
            conversation_id: The conversation ID to export
            output_format: Format for export ("text", "json", "markdown")

        Returns:
            Formatted prompt history string
        """
        self._setup()

        history = self.get_prompt_history(conversation_id)

        if not history:
            return "No prompt history found."

        if output_format == "json":
            import json

            return json.dumps(history, indent=2, default=str)

        elif output_format == "markdown":
            lines = ["# Conversation History", ""]
            for i, entry in enumerate(history, 1):
                cache_mark = "💾" if entry["cache_hit"] else "🔍"
                lines.append(f"## Prompt {i} {cache_mark}")
                lines.append(f"**Prompt**: {entry['prompt']}")
                lines.append(f"**Cache Hit**: {entry['cache_hit']}")
                lines.append(f"**Timestamp**: {entry['created_at']}")
                lines.append("")
            return "\n".join(lines)

        else:  # text format
            lines = [f"Conversation: {conversation_id}", ""]
            for i, entry in enumerate(history, 1):
                cache_mark = "[CACHE HIT]" if entry["cache_hit"] else "[GENIE]"
                lines.append(f"{i}. {cache_mark} {entry['prompt']}")
                lines.append(f"   Timestamp: {entry['created_at']}")
            return "\n".join(lines)

    def clear_prompt_history(self, conversation_id: str | None = None) -> int:
        """
        Clear prompt history for a conversation or entire space.

        Args:
            conversation_id: Specific conversation to clear (None = clear all for space)

        Returns:
            Number of prompts deleted
        """
        self._setup()

        prompt_table_name = self.parameters.prompt_history_table

        if conversation_id:
            delete_sql: str = f"""
                DELETE FROM {prompt_table_name}
                WHERE genie_space_id = %s AND conversation_id = %s
            """
            params = (self.space_id, conversation_id)
        else:
            delete_sql = f"""
                DELETE FROM {prompt_table_name}
                WHERE genie_space_id = %s
            """
            params = (self.space_id,)

        with self._pool.connection() as conn:
            with conn.cursor() as cur:
                cur.execute(delete_sql, params)
                deleted: int = cur.rowcount

                logger.info(
                    "Cleared prompt history",
                    layer=self.name,
                    conversation_id=conversation_id or "all",
                    deleted_count=deleted,
                )

                return deleted

    @property
    def size(self) -> int:
        """Current number of entries in the cache for this Genie space."""
        self._setup()
        count_sql: str = (
            f"SELECT COUNT(*) as count FROM {self.table_name} WHERE genie_space_id = %s"
        )

        with self._pool.connection() as conn:
            with conn.cursor() as cur:
                cur.execute(count_sql, (self.space_id,))
                row: DbRow | None = cur.fetchone()
                return row.get("count", 0) if row else 0

    def stats(self) -> dict[str, int | float | None]:
        """Return cache statistics for this Genie space, including prompt history."""
        self._setup()
        ttl_seconds = self.parameters.time_to_live_seconds
        ttl = self.time_to_live

        # Get semantic cache stats
        cache_stats: dict[str, int | float | None] = {}

        # If TTL is disabled, all entries are valid
        if ttl_seconds is None or ttl_seconds < 0:
            count_sql: str = f"""
                SELECT COUNT(*) as total FROM {self.table_name}
                WHERE genie_space_id = %s
            """
            with self._pool.connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(count_sql, (self.space_id,))
                    row: DbRow | None = cur.fetchone()
                    total = row.get("total", 0) if row else 0
                    cache_stats = {
                        "size": total,
                        "ttl_seconds": None,
                        "similarity_threshold": self.similarity_threshold,
                        "expired_entries": 0,
                        "valid_entries": total,
                    }
        else:
            stats_sql: str = f"""
                SELECT
                    COUNT(*) as total,
                    COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '%s seconds') as valid,
                    COUNT(*) FILTER (WHERE created_at <= NOW() - INTERVAL '%s seconds') as expired
                FROM {self.table_name}
                WHERE genie_space_id = %s
            """

            with self._pool.connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(stats_sql, (ttl_seconds, ttl_seconds, self.space_id))
                    stats_row: DbRow | None = cur.fetchone()
                    cache_stats = {
                        "size": stats_row.get("total", 0) if stats_row else 0,
                        "ttl_seconds": ttl.total_seconds() if ttl else None,
                        "similarity_threshold": self.similarity_threshold,
                        "expired_entries": stats_row.get("expired", 0)
                        if stats_row
                        else 0,
                        "valid_entries": stats_row.get("valid", 0) if stats_row else 0,
                    }

        # Add prompt history stats
        prompt_stats_sql: str = f"""
            SELECT
                COUNT(*) as total_prompts,
                COUNT(*) FILTER (WHERE cache_hit = true) as cache_hit_prompts,
                COUNT(*) FILTER (WHERE cache_hit = false) as cache_miss_prompts,
                COUNT(DISTINCT conversation_id) as total_conversations
            FROM {self.parameters.prompt_history_table}
            WHERE genie_space_id = %s
        """

        with self._pool.connection() as conn:
            with conn.cursor() as cur:
                cur.execute(prompt_stats_sql, (self.space_id,))
                prompt_row: DbRow | None = cur.fetchone()

                if prompt_row:
                    cache_stats["prompt_history"] = {
                        "total_prompts": prompt_row.get("total_prompts", 0),
                        "cache_hit_prompts": prompt_row.get("cache_hit_prompts", 0),
                        "cache_miss_prompts": prompt_row.get("cache_miss_prompts", 0),
                        "total_conversations": prompt_row.get("total_conversations", 0),
                        "cache_hit_rate": (
                            prompt_row.get("cache_hit_prompts", 0)
                            / prompt_row.get("total_prompts", 1)
                            if prompt_row.get("total_prompts", 0) > 0
                            else 0.0
                        ),
                    }

        return cache_stats
