command:
  - /bin/bash
  - -c
  - |
    pip install --index-url https://pypi-proxy.dev.databricks.com/simple/ ./dao_ai-0.1.40-py3-none-any.whl &&
    python -m dao_ai.apps.shared_server
# Databricks Apps listen by default on port 8000

env:
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
  - name: MLFLOW_REGISTRY_URI
    value: "databricks-uc"
  - name: LOG_LEVEL
    value: "INFO"
